### ISSUE TITLE
dr:2000 test fail

### ISSUE THREAD

**Issue by pauleve** [sat-heritage/docker-images#1]
```
$ satex test dr:2000
+ Testing tests/cmu-bmc-barrel6.cnf.gz
+ sudo docker run --rm -v /home/pauleve/orga/projects/sat-heritage/docker-images/tests:/data satex/dr:2000 cmu-bmc-barrel6.cnf.gz
#### dr:2000 ####
# gunzip cmu-bmc-barrel6.cnf.gz...
# ...done
+ /solvers/dr/dr 1 /tmp/cnf
Directional Resolution Algorithm by Irina Rish.
Reading /tmp/cnf...(CNF : 2306 var. 8931 clauses)...Done.
/entrypoint.sh: line 2:    21 Segmentation fault      (core dumped) "/solvers/${SOLVER_PATH}/${SOLVER_CALL}" "${@}"
Traceback (most recent call last):
  File "/home/pauleve/.local/bin/satex", line 11, in <module>
    load_entry_point('satex', 'console_scripts', 'satex')()
  File "/home/pauleve/orga/projects/sat-heritage/docker-images/satex.py", line 455, in main
    return args.func(args)
  File "/home/pauleve/orga/projects/sat-heritage/docker-images/satex.py", line 346, in test_images
    docker_runs(args, images, docker_args, image_args=(dimacs,))
  File "/home/pauleve/orga/projects/sat-heritage/docker-images/satex.py", line 192, in docker_runs
    assert ret == 0 or 10 <= ret <= 20, "Solver failed!"
AssertionError: Solver failed!
```

**Comment by lorensipro** [comment]
Old solvers does not comply to the competition input/output. We simply need to add a wrapper that analyzes the output and writes the magic lines and the magic exit code.
